const dummyRecipes = [{
  imgUrl: 'https://natashaskitchen.com/wp-content/uploads/2020/03/Pan-Seared-Steak-4.jpg',
  title: 'Pan Seared Steak',
  tags: ['breakfast', 'lunch', 'dinner','snack','breakfast', 'lunch', 'dinner',],
  prepTime: '00:05:00',
  cookTime: '00:10:00',
  recipeYield: '2 bowls',
  ingredients: ['steak', 'garlic', 'carrot'],
  rating: '4',
  isFavourite: true,
  description: 'This is the description of this recipe, this is the description of this recipe'
}, {
  imgUrl: 'https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/Crispy-Fried-Chicken_EXPS_TOHJJ22_6445_DR%20_02_03_11b.jpg',
  title: 'Crispy Fried Chicken',
  tags: ['appetizer', 'snack'],
  prepTime: '00:55:00',
  cookTime: '01:30:00',
  recipeYield: '4 disks',
  ingredients: ['chieck', 'crispy powder'],
  rating: '5',
  isFavourite: true,
  description: 'This is the description of this recipe, this is the description of this recipe'
}, {
  imgUrl: 'https://natashaskitchen.com/wp-content/uploads/2020/03/Pan-Seared-Steak-4.jpg',
  title: 'This name is so long that it is truncated',
  tags: ['breakfast', 'lunch', 'dinner'],
  prepTime: '00:05:00',
  cookTime: '00:10:00',
  recipeYield: '2 bowls',
  ingredients: ['steak', 'garlic', 'carrot'],
  rating: '3',
  isFavourite: false,
}, {
  imgUrl: 'https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/Crispy-Fried-Chicken_EXPS_TOHJJ22_6445_DR%20_02_03_11b.jpg',
  title: 'Crispy Fried Chicken',
  tags: ['appetizer', 'snack'],
  prepTime: '00:55:00',
  cookTime: '01:30:00',
  recipeYield: '4 disks',
  ingredients: ['chieck', 'crispy powder'],
  rating: '0',
  isFavourite: true,
  description: 'This is the description of this recipe, this is the description of this recipe'
}, {
  imgUrl: 'https://natashaskitchen.com/wp-content/uploads/2020/03/Pan-Seared-Steak-4.jpg',
  title: 'Pan Seared Steak',
  tags: ['breakfast', 'lunch', 'dinner'],
  prepTime: '00:05:00',
  cookTime: '00:10:00',
  recipeYield: '2 bowls',
  ingredients: ['steak', 'garlic', 'carrot'],
  rating: '2',
  isFavourite: true,
  description: 'This is the description of this recipe, this is the description of this recipe'
}, {
  imgUrl: 'https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/Crispy-Fried-Chicken_EXPS_TOHJJ22_6445_DR%20_02_03_11b.jpg',
  title: 'Crispy Fried Chicken',
  tags: ['appetizer', 'snack'],
  prepTime: '00:55:00',
  cookTime: '01:30:00',
  recipeYield: '4 disks',
  ingredients: ['chieck', 'crispy powder'],
  rating: '1',
  isFavourite: false,
  description: 'This is the description of this recipe, this is the description of this recipe'
},
 {
  imgUrl: 'https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/Crispy-Fried-Chicken_EXPS_TOHJJ22_6445_DR%20_02_03_11b.jpg',
  title: 'Crispy Fried Chicken',
  tags: ['appetizer', 'snack'],
  prepTime: '00:55:00',
  cookTime: '01:30:00',
  recipeYield: '4 disks',
  ingredients: ['chieck', 'crispy powder'],
  rating: '5',
  isFavourite: true,
  description: 'This is the description of this recipe, this is the description of this recipe'
},  {
  imgUrl: 'https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/Crispy-Fried-Chicken_EXPS_TOHJJ22_6445_DR%20_02_03_11b.jpg',
  title: 'Crispy Fried Chicken',
  tags: ['appetizer', 'snack'],
  prepTime: '00:55:00',
  cookTime: '01:30:00',
  recipeYield: '4 disks',
  ingredients: ['chieck', 'crispy powder'],
  rating: '0',
  isFavourite: true,
  description: 'This is the description of this recipe, this is the description of this recipe'
}, {
  imgUrl: 'https://natashaskitchen.com/wp-content/uploads/2020/03/Pan-Seared-Steak-4.jpg',
  title: 'Pan Seared Steak',
  tags: ['breakfast', 'lunch', 'dinner','snack','breakfast', 'lunch', 'dinner',],
  prepTime: '00:05:00',
  cookTime: '00:10:00',
  recipeYield: '2 bowls',
  ingredients: ['steak', 'garlic', 'carrot'],
  rating: '4',
  isFavourite: true,
  description: 'This is the description of this recipe, this is the description of this recipe'
},  {
  imgUrl: 'https://natashaskitchen.com/wp-content/uploads/2020/03/Pan-Seared-Steak-4.jpg',
  title: 'This name is so long that it is truncated',
  tags: ['breakfast', 'lunch', 'dinner'],
  prepTime: '00:05:00',
  cookTime: '00:10:00',
  recipeYield: '2 bowls',
  ingredients: ['steak', 'garlic', 'carrot'],
  rating: '3',
  isFavourite: false,
}, {
  imgUrl: 'https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/Crispy-Fried-Chicken_EXPS_TOHJJ22_6445_DR%20_02_03_11b.jpg',
  title: 'Crispy Fried Chicken',
  tags: ['appetizer', 'snack'],
  prepTime: '00:55:00',
  cookTime: '01:30:00',
  recipeYield: '4 disks',
  ingredients: ['chieck', 'crispy powder'],
  rating: '0',
  isFavourite: true,
  description: 'This is the description of this recipe, this is the description of this recipe'
}, {
  imgUrl: 'https://natashaskitchen.com/wp-content/uploads/2020/03/Pan-Seared-Steak-4.jpg',
  title: 'Pan Seared Steak',
  tags: ['breakfast', 'lunch', 'dinner','snack','breakfast', 'lunch', 'dinner',],
  prepTime: '00:05:00',
  cookTime: '00:10:00',
  recipeYield: '2 bowls',
  ingredients: ['steak', 'garlic', 'carrot'],
  rating: '4',
  isFavourite: true,
  description: 'This is the description of this recipe, this is the description of this recipe'
}, 
]

export default dummyRecipes